from Structures.Environment.Declaration.Declaration import Declaration as Declaration
from _typeshed import Incomplete

class DependencyManager:
    loaded: Incomplete
    loading: Incomplete
    environment: Incomplete
    type_checker: Incomplete
    folder: Incomplete
    def __init__(self, folder: str) -> None: ...
    def is_loaded(self, decl_file_name: str) -> bool: ...
    def check_dependencies_loaded(self, dependencies: list[str]) -> bool: ...
    def load_isolated(self, decl_file_name: str, declaration: Declaration): ...
    def load(self, decl_file_name: str): ...
