from Structures.Name import *
from Structures.Expression.Level import *
from Structures.Expression.Expression import *
from Structures.Environment.Declaration.Declaration import *
from Structures.Environment.ReducibilityHint import *
from _typeshed import Incomplete
from typing import Any

tag_to_level_class: Incomplete
tag_to_expr_class: Incomplete
json_type: Incomplete

def getObj(tag: str, args: dict[str, Any]) -> Any: ...
def deserialize_expr(json_obj: dict[str, 'json_type'], subexprs: list[Expression | None]) -> Expression | Level: ...
def deserialize_list(json_list: list[json_type], subexprs: list[Expression | None] | None): ...
def deserialize_json(json_obj: json_type, subexprs_or_none: list[Expression | None] | None) -> Any: ...
def deserialize_declaration_profile(json_obj: json_type) -> tuple[list[str], Declaration]: ...
def from_file(file_path: str) -> tuple[list[str], Declaration]: ...
