import abc
from _typeshed import Incomplete

__all__ = ['Name', 'Anonymous', 'SubName']

class Name(metaclass=abc.ABCMeta):
    def defEq(self, other: Name) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Anonymous(Name): ...

class SubName(Name):
    str: Incomplete
    anc: Incomplete
    def __init__(self, anc: Name, str: str) -> None: ...
