from Structures.Expression.Expression import Expression as Expression, FVar as FVar
from _typeshed import Incomplete

class LocalContext:
    fvars: Incomplete
    def __init__(self) -> None: ...
    def add_fvar(self, fvar: FVar): ...
    def remove_fvar(self, fvar: FVar): ...
    def get_fvar_type(self, fvar: FVar) -> Expression: ...
    def get_fvar_value(self, fvar: FVar) -> Expression | None: ...
    def clear(self) -> None: ...
    def is_empty(self) -> bool: ...
